# Generated by Django 5.1.4 on 2024-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ano_ingresso', models.IntegerField()),
                ('foto', models.ImageField(upload_to='alunos_fotos/')),
                ('materias', models.ManyToManyField(related_name='alunos', to='materias.materia')),
            ],
        ),
    ]
